### ISSUE TITLE
Add @types/express as peerDependency

### ISSUE THREAD

**Issue by Xiphe** [fgnass/typed-rpc#1]
We tried to use the middleware without express and then the typing got lost.

**Comment by fgnass** [comment]
I think the typings got lost because I added an export map to package.json which is not yet supported by TypeScript. As a workaround I added "typesVersions" which seems to work fine even when @types/express are not installed.

**Comment by fgnass** [comment]
Published as typed-rpc@1.0.1 ... let me know if this works!

**Comment by Xiphe** [comment]
yes, works now 👍 

I'm having a hard time getting the package to work in a project with `"module": "CommonJS"` though. 😕 
Switching to "es6" makes other parts of the project explode. I think I need to up my native node es modules game :)

**Comment by fgnass** [comment]
No worries, I'll add a cjs build!

**Comment by Xiphe** [comment]
That'll be awesome! Didn't meant to re-open btw :)

**Comment by fgnass** [comment]
Okay, so typed-rpc@1.0.2 now contains a cjs build. I hope it works, it's my first hybrid module.

**Comment by Xiphe** [comment]
Thank a lot!

with my current environment, typescript does not pick up entries from `exports` in `package.json` (rel https://github.com/microsoft/TypeScript/issues/33079 ?)

But importing the entries directly from `typed-rpc/lib/cjs/client` works good enough 👍

**Comment by Xiphe** [comment]
hm, the server part works.
