### ISSUE TITLE
Support for AbortSignal when calling RPC endpoints

### ISSUE THREAD

**Issue by macalinao** [fgnass/typed-rpc#14]
It would be great if the RPC client somehow allowed passing in an AbortSignal to cancel requests.

Not sure what the syntax would look like here-- maybe something like `client.myMethod.withSignal(signal).call(...args)`?

**Comment by fgnass** [comment]
I created a branch that supports aborting requests: https://github.com/fgnass/typed-rpc/tree/abort-signals#aborting-requests

Would that API work for you?

**Comment by macalinao** [comment]
Yes this works. Thank you!

**Comment by fgnass** [comment]
Feature landed in 4.1.0
