### ISSUE TITLE
console.log on missing method possibly leaks internal info in logs

### ISSUE THREAD

**Issue by erkkah** [fgnass/typed-rpc#15]
This seems to be a debug log left? In my case (cloudflare), this leads to the service object getting dumped (depends on runtime, I guess) to the logs.

https://github.com/fgnass/typed-rpc/blob/ca38957c811880b0ea3e8538088fb0a03020b2f1/src/server.ts#L115

**Comment by erkkah** [comment]
Hey, that was fast! Thanks for the great package.

**Comment by fgnass** [comment]
Published as typed-rpc@5.0.1
