### ISSUE TITLE
Params as object

### ISSUE THREAD

**Issue by beautyfree** [fgnass/typed-rpc#19]
I'm using this library on client with backend on rust which has standard format for named parameters

but I see what this library send params as array of objects, but not an object (like in spec https://www.jsonrpc.org/specification#examples)
```json
"method":"my_referrals","params":[{"user":"devall.key","timed_signature":{"timestamp":0,"signature":""}}]
```

is there a way to support standard format?

**Comment by fgnass** [comment]
Named parameters are not supported, as such a concept does not exist in JavaScript. You could implement a custom transport though to modify the parameters before they are sent:

```ts
const transport = fetchTransport({url: "https://example.com/api"})
  const client = rpcClient<Service>({
    transport: async (req, abortSignal) => {
      return transport({...req, params: req.params[0]}, abortSignal);
    },
  });
```

**Comment by beautyfree** [comment]
oh, thank you! you saved my day
