### ISSUE TITLE
source-maps point to `src` which is not published

### ISSUE THREAD

**Issue by Xiphe** [fgnass/typed-rpc#2]
Currently the source-maps point to `"../../src/client.ts"` etc. but `.npmignore` excludes the `src` from being published.

This causes errors for example with parcel:

```
Could not load source file "../../src/client.ts" in source map of "../node_modules/typed-rpc/lib/cjs/client.js".
```

**Comment by fgnass** [comment]
Good catch! typed-rpc@1.0.3 now includes the sources.
