### ISSUE TITLE
Bug: id is not unique

### ISSUE THREAD

**Issue by thegecko** [fgnass/typed-rpc#28]
This library used `Date.now()` for the message id which is only unique so long as the user creates less than 1 request per millisecond.

If many requests are created (e.g. by sending 10,000 requests in a loop) then multiple requests use the same id.

This is problematic for async wrappers such as https://github.com/fgnass/typed-rpc/tree/feat/ws because its not possible to determine the correct callback to use or cases can arise where a callback is used and then further responses arrive which cannot be handled.

PR added to tackle this in #29

**Comment by fgnass** [comment]
Thank you! I noticed the same when working on the feat/ws branch. I therefore changed the ID generation to a sequence that gets incremented with each request: https://github.com/fgnass/typed-rpc/blob/feat/ws/src/client.ts#L183. Do you think this is good enough, or can you think of situations where a custom implementation would be required?

**Comment by thegecko** [comment]
> do you think [incrementing the id] is good enough?

Hmm, if both ends of the same transport layer use different instances of this library, the IDs could still clash if just incrementing. 

I think allowing consumers to supply their own id implementation is important depending on their needs.

**Comment by fgnass** [comment]
True, users might choose to use multiple client instances or create new ones for each request. Would you mind basing your PR against the feat/ws branch instead?

**Comment by thegecko** [comment]
> True, users might choose to use multiple client instances or create new ones for each request. Would you mind basing your PR against the feat/ws branch instead?

I can, is that being merged soon, then? I could also wait until its merged into main and then rebase?

I'm keen to find the quickest route to get this released ;)

**Comment by thegecko** [comment]
https://github.com/fgnass/typed-rpc/pull/30

**Comment by fgnass** [comment]
You can test the preview release via `npm i https://pkg.pr.new/fgnass/typed-rpc@79af998` – If everything works, we can merge this into main.

**Comment by thegecko** [comment]
That command fails for me with:

`unable to get local issuer certificate`

**Comment by thegecko** [comment]
I've built this branch from source and linked it to my test project. All seem well.

**Comment by fgnass** [comment]
landed in 6.1.1
