### ISSUE TITLE
Discussion: Caching

### ISSUE THREAD

**Issue by Xiphe** [fgnass/typed-rpc#3]
I use this lib to have a typed contract between my web client and the server. 
There are some "methods" that could theoretically be cached in CDN and on Clients since they don't have any parameters or user specific headers.

IIRC since all remove calls are done with a `POST` request they'll always hit the server

I understand that it somehow violates the `call` part but would be interested in how you see this @fgnass.

**Comment by fgnass** [comment]
The latest release now supports custom transports. This could be used to perform GET requests for methods that don't have any arguments.

**Comment by Xiphe** [comment]
Interesting! Thanks for letting me know 👍
